export const AVATAR_LIST_INTERVAL_DELAY = 100;
export const AVATAR_LIST_VISIBLE_CHARACTERS_COUNT = 5;
export const AVATAR_LIST_HALF_VISIBLE_CHARACTERS_COUNT = Math.floor(AVATAR_LIST_VISIBLE_CHARACTERS_COUNT / 2);
